LocadoraDigitalMVC/LocadoraDigitalMVC/Controllers/DevolucoesController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using LocadoraDigitalMVC.Entities;
using LocadoraDigitalMVC.Repository.EntityFramework.Context;
using LocadoraDigitalMVC.Repository.EntityFramework;
using System.Collections.Generic;
using System;
using LocadoraDigitalMVC.IRepository;
using LocadoraDigitalMVC.IBusiness;
using LocadoraDigitalMVC.Business;

namespace LocadoraDigitalMVC.Controllers
{
    public class DevolucoesController : Controller
    {
        private LocadoraDigitalMVCContext d1b1 = new LocadoraDigitalMVCContext();
        private DevolucaoRepository d1b = new DevolucaoRepository();

        private readonly IDevolucaoBusiness devolucaoBusiness;

        public DevolucoesController(IDevolucaoBusiness _devolucaoBusiness)
        {
            this.devolucaoBusiness = _devolucaoBusiness;
        }

        public ActionResult Index(string nomeCliente, string nomeFilme, DateTime? dtLocacao, DateTime? dtDevolucao)
        {
            //MUDAR ISSO
            var ClienteLst = new List<string>();
            var FilmeLst = new List<string>();

            var ClienteQry = from d in d1b1.Clientes
                             orderby d.Nome
                             select d.Nome;

            var FilmeQry = from d in d1b1.Filmes
                           orderby d.Nome
                           select d.Nome;

            ClienteLst.AddRange(ClienteQry.Distinct());
            FilmeLst.AddRange(FilmeQry.Distinct());
            ViewBag.nomeCliente = new SelectList(ClienteLst);
            ViewBag.nomeFilme = new SelectList(FilmeLst);

            
            return View(devolucaoBusiness.GetByFilter(nomeCliente, nomeFilme, dtLocacao, dtDevolucao));
        }


        public ActionResult Details(int id)
        {
            Devolucao devolucao = devolucaoBusiness.Get(id);
            if (devolucao == null)
            {
                return HttpNotFound();
            }
            return View(devolucao);
        }

       
    }
}
 

LocadoraDigitalMVC/LocadoraDigitalMVC/Views/Devolucoes/Details.cshtml
@model LocadoraDigitalMVC.Entities.Devolucao

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Devolucao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Locacao.Filme.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Locacao.Filme.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Locacao.Cliente.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Locacao.Cliente.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Locacao.dtLocacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Locacao.dtLocacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Locacao.dtDevolucao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Locacao.dtDevolucao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtDev)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtDev)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Multa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Multa)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

LocadoraDigitalMVC/LocadoraDigitalMVC/Views/Devolucoes/Index.cshtml
@model IEnumerable<LocadoraDigitalMVC.Entities.Devolucao>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @using (Html.BeginForm("Index", "Devolucoes", FormMethod.Get))
    {
    <p>
        Cliente: @Html.DropDownList("nomeCliente", "All")
        Filme: @Html.DropDownList("nomeFilme", "All")
        Locação: @Html.TextBox("dtLocacao")
        Devolução: @Html.TextBox("dtDevolucao")
        <br />
        <input type="submit" value="Buscar" />
    </p>
    }

    </p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Locacao.Filme.Nome)
        </th>
        <th>
            Cliente
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Locacao.dtLocacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Locacao.dtDevolucao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dtDev)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Multa)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Locacao.Filme.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Locacao.Cliente.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Locacao.dtLocacao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Locacao.dtDevolucao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dtDev)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Multa)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.Id })
        </td>
    </tr>
}

</table>