LocadoraDigitalMVC/LocadoraDigitalMVC/Controllers/LocacoesController.cs
using System.Web.Mvc;
using LocadoraDigitalMVC.Entities;
using LocadoraDigitalMVC.IBusiness;
using System;
using System.Collections.Generic;
using LocadoraDigitalMVC.Repository.EntityFramework.Context;
using System.Linq;

namespace LocadoraDigitalMVC.Controllers
{
    public class LocacoesController : Controller
    {
        private LocadoraDigitalMVCContext mudar = new LocadoraDigitalMVCContext();
        //private LocacaoRepository locacaoBusiness = new LocacaoRepository();

        private readonly ILocacaoBusiness locacaoBusiness;
        
        public LocacoesController(ILocacaoBusiness _locacaoBusiness)
        {
            this.locacaoBusiness = _locacaoBusiness;
        }

        public ActionResult Index(string nomeCliente, string nomeFilme, DateTime? dtLocacao, DateTime? dtDevolucao)
        {
            //MUDAR ISSO
            var ClienteLst = new List<string>();
            var FilmeLst = new List<string>();

            var ClienteQry = from d in mudar.Clientes
                           orderby d.Nome
                           select d.Nome;

            var FilmeQry = from d in mudar.Filmes
                           orderby d.Nome
                           select d.Nome;

            ClienteLst.AddRange(ClienteQry.Distinct());
            FilmeLst.AddRange(FilmeQry.Distinct());
            ViewBag.nomeCliente = new SelectList(ClienteLst);
            ViewBag.nomeFilme = new SelectList(FilmeLst);

            return View(locacaoBusiness.GetByFilter(nomeCliente, nomeFilme, dtLocacao, dtDevolucao));
        }
        
        public ActionResult Details(int id)
        {
            Locacao locacao = locacaoBusiness.Get(id);
            if (locacao == null)
            {
                return HttpNotFound();
            }
            return View(locacao);
        }

        public ActionResult Create()
        {
            var filmesDisp = from f in mudar.Filmes
                             select f;
            filmesDisp = filmesDisp.Where(x => x.Status == true);

            ViewBag.ClienteId = new SelectList(mudar.Clientes, "Id", "Nome");
            
            ViewBag.FilmeId = new SelectList(filmesDisp, "Id", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ClienteId,FilmeId,dtLocacao,dtDevolucao")] Locacao locacao)
        {
            if (ModelState.IsValid)
            {
                locacaoBusiness.Create(locacao);
                return RedirectToAction("Index");
            }

            ViewBag.ClienteId = new SelectList(mudar.Clientes, "Id", "Nome", locacao.ClienteId);
            ViewBag.FilmeId = new SelectList(mudar.Filmes, "Id", "Nome", locacao.FilmeId);
            return View(locacao);
        }

        public ActionResult Edit(int id)
        {
            Locacao locacao = locacaoBusiness.Get(id);
            if (locacao == null)
            {
                return HttpNotFound();
            }

            ViewBag.ClienteId = new SelectList(mudar.Clientes, "Id", "Nome", locacao.ClienteId);
            ViewBag.FilmeId = new SelectList(mudar.Filmes, "Id", "Nome", locacao.FilmeId);
            return View(locacao);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ClienteId,FilmeId,dtLocacao,dtDevolucao")] Locacao locacao)
        {
            if (ModelState.IsValid)
            {
                locacaoBusiness.Update(locacao);
                return RedirectToAction("Index");
            }
            ViewBag.ClienteId = new SelectList(mudar.Clientes, "Id", "Nome", locacao.ClienteId);
            ViewBag.FilmeId = new SelectList(mudar.Filmes, "Id", "Nome", locacao.FilmeId);
            return View(locacao);
        }
        
        public ActionResult Devolucao(int id)
        {
            Locacao locacao = locacaoBusiness.Get(id);
            if (locacao == null)
            {
                return HttpNotFound();
            }
            return View(locacao);
        }

        [HttpPost, ActionName("Devolucao")]
        [ValidateAntiForgeryToken]
        public ActionResult Devolvido(int id)
        {
            Locacao locacao = locacaoBusiness.Get(id);
           
            locacaoBusiness.Devolucao(locacao);
            return RedirectToAction("Index","Devolucoes");
        }

     }
}

LocadoraDigitalMVC/LocadoraDigitalMVC/Views/Locacoes/Create.cshtml
@model LocadoraDigitalMVC.Entities.Locacao

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Locacao</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClienteId, "ClienteId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClienteId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClienteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilmeId, "FilmeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FilmeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FilmeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtLocacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtLocacao, new { htmlAttributes = new { @class = "form-control" } })
               
                @Html.ValidationMessageFor(model => model.dtLocacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtDevolucao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtDevolucao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtDevolucao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LocadoraDigitalMVC/LocadoraDigitalMVC/Views/Locacoes/Details.cshtml
@model LocadoraDigitalMVC.Entities.Locacao

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Locacao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Filme.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Filme.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtLocacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtLocacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtDevolucao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtDevolucao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LocadoraDigitalMVC/LocadoraDigitalMVC/Views/Locacoes/Devolucao.cshtml
@model LocadoraDigitalMVC.Entities.Locacao

@{
    ViewBag.Title = "Devolucao";
}

<h2>Devolução</h2>

<h3>Deseja realmente cadastrar a devolução desse filme?</h3>
<div>
    <h4>Locacao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Filme.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Filme.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtLocacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtLocacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dtDevolucao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dtDevolucao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LocadoraDigitalMVC/LocadoraDigitalMVC/Views/Locacoes/Edit.cshtml
@model LocadoraDigitalMVC.Entities.Locacao

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Locacao</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteId, "ClienteId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClienteId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClienteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilmeId, "FilmeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FilmeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FilmeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtLocacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtLocacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtLocacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtDevolucao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtDevolucao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dtDevolucao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LocadoraDigitalMVC/LocadoraDigitalMVC/Views/Locacoes/Index.cshtml
@model IEnumerable<LocadoraDigitalMVC.Entities.Locacao>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @using (Html.BeginForm("Index", "Locacoes", FormMethod.Get))
    {
    <p>
        Cliente: @Html.DropDownList("nomeCliente", "All")
        Filme: @Html.DropDownList("nomeFilme", "All")
        Locação: @Html.TextBox("dtLocacao")
        Devolução: @Html.TextBox("dtDevolucao")
        <br />
        <input type="submit" value="Buscar" />
    </p>
    }

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cliente.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Filme.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dtLocacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dtDevolucao)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Filme.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dtLocacao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dtDevolucao)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Devolução", "Devolucao", new { id=item.Id })
        </td>
    </tr>
}

</table>