LocadoraDigitalMVC/LocadoraDigitalMVC/Controllers/FilmesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LocadoraDigitalMVC.Entities;
using LocadoraDigitalMVC.Repository.EntityFramework.Context;
using LocadoraDigitalMVC.Repository.EntityFramework;
using LocadoraDigitalMVC.IBusiness;

namespace LocadoraDigitalMVC.Controllers
{
    public class FilmesController : Controller
    {
        private LocadoraDigitalMVCContext mudar = new LocadoraDigitalMVCContext();
        //private FilmeRepository db = new FilmeRepository();

        private readonly IFilmeBusiness filmeBusiness;
        public FilmesController(IFilmeBusiness _filmeBusiness)
        {
            this.filmeBusiness = _filmeBusiness;
        }

        public ActionResult Index(string nomeFilme,string nomeGenero, string status)
        {
            //MUDAR ISSO 
            var GenreLst = new List<string>();

            var GenreQry = from d in mudar.Generos
                           orderby d.Descricao
                           select d.Descricao;
            GenreLst.AddRange(GenreQry.Distinct());
            ViewBag.nomeGenero = new SelectList(GenreLst);

            return View(filmeBusiness.GetByFilter(nomeFilme, nomeGenero, status));
            //return View(filmeBusiness.GetAll());
          
        }

        public ActionResult Details(int id)
        {
            Filme filme = filmeBusiness.Get(id);
            if (filme == null)
            {
                return HttpNotFound();
            }
            return View(filme);
        }

        public ActionResult Create()
        {
            ViewBag.GeneroId = new SelectList(mudar.Generos, "Id", "Descricao");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,GeneroId")] Filme filme)
        {
            if (ModelState.IsValid)
            {
                
                filmeBusiness.Create(filme);
                return RedirectToAction("Index");
            }

            ViewBag.GeneroId = new SelectList(mudar.Generos, "Id", "Descricao", filme.GeneroId);
            return View(filme);
        }

        public ActionResult Edit(int id)
        {
            Filme filme = filmeBusiness.Get(id);
            if (filme == null)
            {
                return HttpNotFound();
            }
            ViewBag.GeneroId = new SelectList(mudar.Generos, "Id", "Descricao", filme.GeneroId);
            return View(filme);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,GeneroId")] Filme filme)
        {
            if (ModelState.IsValid)
            {
                
                filmeBusiness.Update(filme);
                return RedirectToAction("Index");
            }
            ViewBag.GeneroId = new SelectList(mudar.Generos, "Id", "Descricao", filme.GeneroId);
            return View(filme);
        }

        public ActionResult Delete(int id)
        {
           
            Filme filme = filmeBusiness.Get(id);
            if (filme == null)
            {
                return HttpNotFound();
            }
            return View(filme);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Filme filme = filmeBusiness.Get(id);
            filmeBusiness.Delete(filme);
            return RedirectToAction("Index");
        }

    }
}

LocadoraDigitalMVC/LocadoraDigitalMVC/Views/Filmes/Create.cshtml
@model LocadoraDigitalMVC.Entities.Filme

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Filme</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GeneroId, "GeneroId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GeneroId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GeneroId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LocadoraDigitalMVC/LocadoraDigitalMVC/Views/Filmes/Delete.cshtml
@model LocadoraDigitalMVC.Entities.Filme

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Filme</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genero.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LocadoraDigitalMVC/LocadoraDigitalMVC/Views/Filmes/Details.cshtml
@model LocadoraDigitalMVC.Entities.Filme

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Filme</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genero.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LocadoraDigitalMVC/LocadoraDigitalMVC/Views/Filmes/Edit.cshtml
@model LocadoraDigitalMVC.Entities.Filme

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Filme</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GeneroId, "GeneroId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GeneroId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GeneroId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LocadoraDigitalMVC/LocadoraDigitalMVC/Views/Filmes/Index.cshtml
@model IEnumerable<LocadoraDigitalMVC.Entities.Filme>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @using (Html.BeginForm("Index", "Filmes", FormMethod.Get))
    {
    <p>
        Filme: @Html.TextBox("nomeFilme")
        Gênero: @Html.DropDownList("nomeGenero", "All")
        Status:
        @Html.RadioButton("status", "disponivel") disponível
        @Html.RadioButton("status", "alugado") alugado
        
        <br />
        <input type="submit" value="Buscar" />
    </p>
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genero.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genero.Descricao)
        </td>
        <td>
            
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>